---
tasks:
# Git
- category: git
  name: submodules
  description: Update submodules
  path: "${PWD}"
  action: update
  command: git submodule update --remote --merge
  args: []
  environments: {}

# Mastodon
- category: project
  name: mastodon
  description: Start Mastodon project
  path: "${PWD}/projects/mastodon"
  action: start
  command: docker compose -f .devcontainer/compose.yaml up -d
  args: []
  environments: {}
- category: project
  name: mastodon
  description: Setup Mastodon project
  path: "${PWD}/projects/mastodon"
  action: setup
  command: docker compose -f .devcontainer/compose.yaml exec app bin/setup
  args: []
  environments: {}
- category: project
  name: mastodon
  description: Run Dev for Mastodon project
  path: "${PWD}/projects/mastodon"
  action: dev
  command: docker compose -f .devcontainer/compose.yaml exec app bin/dev
  args: []
  environments: {}
- category: project
  name: mastodon
  description: Stop Mastodon project
  path: "${PWD}/projects/mastodon"
  action: stop
  command: docker compose -f .devcontainer/compose.yaml down
  args: []
  environments: {}

# Chatwoot
- category: project
  name: chatwoot
  description: Build Chatwoot project
  path: "${PWD}/projects/chatwoot"
  action: build
  command: |
    cp .env.example .env
    docker compose build base
    docker compose build
    docker compose run --rm rails bundle exec rails db:chatwoot_prepare
  args: []
  environments: {}
- category: project
  name: chatwoot
  description: Start Chatwoot project
  path: "${PWD}/projects/chatwoot"
  action: start
  command: docker compose up -d
  args: []
  environments: {}
- category: project
  name: chatwoot
  description: Stop Chatwoot project
  path: "${PWD}/projects/chatwoot"
  action: stop
  command: docker compose down
  args: []
  environments: {}