---
tasks:
# Git
- category: git
  name: submodule
  description: Update submodules
  path: "${PWD}"
  action: update
  command: git submodule update --remote

# Containers
- category: collection
  name: container
  description: Start container collection
  path: "${PWD}/containers"
  action: start
  command: docker compose up -d
- category: collection
  name: container
  description: Stop container collection
  path: "${PWD}/containers"
  action: stop
  command: docker compose down

# Mastodon
- category: project
  name: mastodon
  description: Start Mastodon project
  path: "${PWD}/projects/mastodon"
  action: start
  command: docker compose -f .devcontainer/compose.yaml up -d
- category: project
  name: mastodon
  description: Setup Mastodon project
  path: "${PWD}/projects/mastodon"
  action: setup
  command: docker compose -f .devcontainer/compose.yaml exec app bin/setup
- category: project
  name: mastodon
  description: Run Dev for Mastodon project
  path: "${PWD}/projects/mastodon"
  action: dev
  command: docker compose -f .devcontainer/compose.yaml exec app bin/dev
- category: project
  name: mastodon
  description: Stop Mastodon project
  path: "${PWD}/projects/mastodon"
  action: stop
  command: docker compose -f .devcontainer/compose.yaml down

# Chatwoot
- category: project
  name: chatwoot
  description: Build Chatwoot project
  path: "${PWD}/projects/chatwoot"
  action: build
  command: |
    cp .env.example .env
    docker compose build base
    docker compose build
    docker compose run --rm rails bundle exec rails db:chatwoot_prepare
- category: project
  name: chatwoot
  description: Start Chatwoot project
  path: "${PWD}/projects/chatwoot"
  action: start
  command: docker compose up -d
- category: project
  name: chatwoot
  description: Stop Chatwoot project
  path: "${PWD}/projects/chatwoot"
  action: stop
  command: docker compose down

# Discourse
- category: project
  name: discourse
  description: Init Discourse project
  path: "${PWD}/projects/discourse"
  action: init
  command: d/boot_dev --init
- category: project
  name: discourse
  description: Run boot for Discourse project
  path: "${PWD}/projects/discourse"
  action: boot
  command: d/boot_dev
- category: project
  name: discourse
  description: Run dev for Discourse project
  path: "${PWD}/projects/discourse"
  action: dev
  command: d/rails s
- category: project
  name: discourse
  description: A separate terminal for Discourse project
  path: "${PWD}/projects/discourse"
  action: cli
  command: d/ember-cli
- category: project
  name: discourse
  description: Stop Discourse project
  path: "${PWD}/projects/discourse"
  action: stop
  command: d/shutdown_dev

# Forem
- category: project
  name: forem
  description: Build Forem project
  path: "${PWD}/projects/forem"
  action: build
  command: dip provision
- category: project
  name: forem
  description: Start Forem project
  path: "${PWD}/projects/forem"
  action: start
  command: dip rails s